<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQNKiuLa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQNKiuLa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQNKiuLa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQNKiuLa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQNKiuLa\App_KernelDevDebugContainer([
    'container.build_hash' => 'QNKiuLa',
    'container.build_id' => '28e98037',
    'container.build_time' => 1653060902,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQNKiuLa');
